Ft welcome screen
Lambda-School-Labs/shopping-cart-fe pull request #4
Opened 2020-05-12 01:35 UTC by bkandaris

## Description
Describe change or new feature here.
## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist
Remove any items which are not applicable.
- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [ ] New and existing unit tests pass locally with my changes
## Link to Trello card

2020-05-13 00:20 UTC, ChiragThesia commented on src/state/reducers/logoReducer.js
> +// import { UPLOAD_LOGO } from '../actionTypes';
Delete commented out code please!

2020-05-13 00:27 UTC, ChiragThesia approved these changes

2020-05-13 00:27 UTC, MatthewVaccaro commented
Potential probs
Zipcode should only take numbers & a total of 5 characters. My assumption is Chirag will build the scheme to require those pieces and if a user adds in letters or more than 5 characters then it will error

Chore
The touch validation you have on fields turns on the second you start typing on any field.

2020-05-13 00:30 UTC, ChiragThesia commented
@MatthewVaccaro I am just expecting a number. I will find a way to limit if need be, but for now there is no max.

2020-05-13 00:38 UTC, ChiragThesia submitted a review, later dismissed
Looks good. We just need to discuss the back end aspect and how this will connect. We'll fix it this Friday!

2020-05-13 00:41 UTC, ChiragThesia commented
@erferguson @bkandaris can you please check mark the read me up top. Thanks

2020-05-13 02:04 UTC, bkandaris commented
Deleted unnecessary comments, fixed error handling on 'welcome', fixed redux issue with the logo.

2020-05-13 17:09 UTC, Cireimu requested changes
Checked out the welcome-screen and color-picker components.
There's a couple of things I want to be changed before we merge, besides these small things your guys' stuff looks pretty good. The main thing is I need you to pull from `develop` and resolve the merge conflicts, I can help guide you through which changes to accept.

Some notes:

- When I checked out your color picker component on its own route and the brand view route, I came across this warning message `Warning: Invalid DOM property 'classname'. Did you mean 'className'? ` Please fix this

- It also looks like your brand view route is a rough version of what it's supposed to be. Let's create a new task for that on the Trello, which can be started at any time but will need to be finished.

- Some sort of clear indicationon what's optional and what's required might be good to add, at the moment the fields that appear to be optional don't give to much of a clear signal that they are. It doesn't need to be done now, can be saved for a chore, but I thought it was worth noting nonetheless.

![classname to className croped](https://user-images.githubusercontent.com/51389138/81843189-17ccea80-9502-11ea-883d-13255e63143e.png)

2020-05-13 23:49 UTC, Cireimu approved these changes
Looks good, I have some notes for later, but looks good to go. Keep up the good work!

2020-05-14 01:38 UTC, MatthewVaccaro approved these changes
Other than the small visual bug/chore everything works
- The welcome screen has the correct inline valuation & when the submit button is click the information is store in redux correctly
- The brand page updates the visuals with the selected logo, the brand color picker works perectly and both store in redux correctly.

2020-05-14 01:41 UTC, merged