Ch testing createproduct
Lambda-School-Labs/shopping-cart-fe pull request #51
Opened 2020-06-25 00:27 UTC by bkandaris

## Description
Wrote 33 render tests for the 'create product' screen. These DO NOT include tests for conditionally rendered pieces / error messaging. These may be written in the near future depending on our test coverage percentage.

P.S. Big props to Matt, this component had a TON of logic and child components.

## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/iW8IpHIT

2020-06-25 18:12 UTC, Cireimu requested changes
CreateProduct test runs perfectly and passes, however, the brandview test does not pass, and it looks like the reason for that is the lack of matching test-dataid on the correlating brandview components areas.

I need you to make sure these tests pass before I will merge.
![no test-dataid found](https://user-images.githubusercontent.com/51389138/85775644-d02aa880-b6d4-11ea-893e-2bc2784ff07d.PNG)

2020-06-25 21:53 UTC, bkandaris commented
Not sure what happened, but all of the 'data-testid' properties disappeared? I added them again and made sure there were no merge conflicts.

2020-06-26 01:04 UTC, Cireimu approved these changes

2020-06-27 00:06 UTC, bkandaris commented
> CreateProduct test runs perfectly and passes, however, the brandview test does not pass, and it looks like the reason for that is the lack of matching test-dataid on the correlating brandview components areas.
> 
> I need you to make sure these tests pass before I will merge.
> ![no test-dataid found](https://user-images.githubusercontent.com/51389138/85775644-d02aa880-b6d4-11ea-893e-2bc2784ff07d.PNG)

![image](https://user-images.githubusercontent.com/52390565/85909538-8337f680-b7e8-11ea-9180-f6d0e18910cf.png)

Just rechecked and everything is passing, should be good to go.

2020-06-27 00:07 UTC, merged