Ch delete unused
Lambda-School-Labs/shopping-cart-fe pull request #55
Opened 2020-07-06 23:20 UTC by bkandaris

## Description
Went through the application to delete files that we aren't using and/or have replaced with our own code.

Went through the application to make sure none of the files deleted were creating new errors or causing breaking changes.

## Checklist
Remove any items which are not applicable.
- [x] My changes generate no new warnings

## Link to Trello card
https://trello.com/c/tC0Q0Fyz

2020-07-07 22:46 UTC, Cireimu requested changes
Seems good, just need you to remove support from the imports as well as remove the support route

![need to remove support](https://user-images.githubusercontent.com/51389138/86852088-f9e6b680-c068-11ea-801e-a9893a5a6d0d.PNG)

2020-07-09 23:29 UTC, ChiragThesia submitted a review, later dismissed

2020-07-11 00:11 UTC, bkandaris commented
> Seems good, just need you to remove support from the imports as well as remove the support route
> 
> ![need to remove support](https://user-images.githubusercontent.com/51389138/86852088-f9e6b680-c068-11ea-801e-a9893a5a6d0d.PNG)

Just fixed this I think it's good to go

2020-07-11 00:21 UTC, Cireimu submitted a review, later dismissed
Looking good!

2020-07-11 00:30 UTC, merged