profile view testing
Lambda-School-Labs/shopping-cart-fe pull request #56
Opened 2020-07-11 00:08 UTC by bkandaris

## Description
Wrote render tests for the profile View page (29 total)

## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes

2020-07-13 23:22 UTC, Cireimu submitted a review, later dismissed

2020-07-14 00:58 UTC, mjedwards submitted a review, later dismissed

2020-07-14 22:39 UTC, Cireimu requested changes
Need you to first correct an issue that isn't allowing my frontend to load then we can merge.
Side note: it seems like Andy's edit profile page isn't working at all and or isn't there so we will need to get that figured out.
![cannot resolve editprofile](https://user-images.githubusercontent.com/51389138/87483250-227e2b80-c5e8-11ea-8673-ae8da156ef9e.PNG)

2020-07-14 23:39 UTC, bkandaris commented
> Need you to first correct an issue that isn't allowing my frontend to load then we can merge.
> Side note: it seems like Andy's edit profile page isn't working at all and or isn't there so we will need to get that figured out.
> ![cannot resolve editprofile](https://user-images.githubusercontent.com/51389138/87483250-227e2b80-c5e8-11ea-8673-ae8da156ef9e.PNG)

Not sure what is going on with the 'EditProfile' component? I deleted the import in App.js so the app runs. 

> Need you to first correct an issue that isn't allowing my frontend to load then we can merge.
> Side note: it seems like Andy's edit profile page isn't working at all and or isn't there so we will need to get that figured out.
> ![cannot resolve editprofile](https://user-images.githubusercontent.com/51389138/87483250-227e2b80-c5e8-11ea-8673-ae8da156ef9e.PNG)


Looks like after Andy's changes merged to develop everything is working/looking good!

2020-07-15 22:55 UTC, merged