Ft inventory
Lambda-School-Labs/shopping-cart-fe pull request #7
Opened 2020-05-13 23:51 UTC by mjedwards

## Description
Describe change or new feature here.
## Type of change
Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist
Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project

## Link to Trello card

2020-05-15 00:55 UTC, erferguson requested changes
just minor edits re: removing commented out code. good work, Mike!

2020-05-15 00:55 UTC, erferguson commented on src/components/Navbar.js
> +              {/* <a href='#'>Home</a> */}
can probably be removed?

2020-05-15 00:55 UTC, erferguson commented on src/components/Navbar.js
> +              {/* <a href='#'>Store</a> */}
can probably be removed?

2020-05-15 00:55 UTC, erferguson commented on src/components/Navbar.js
> +              {/* <a href='#'>Account</a> */}
can be removed?

2020-05-15 00:55 UTC, erferguson commented on src/components/Navbar.js
> +              {/* <a href='#'>Profile</a> */}
can be removed?

2020-05-15 00:55 UTC, erferguson commented on src/components/Navbar.js
> +      {/* <Divider
97-101, can be removed?

2020-05-15 00:55 UTC, erferguson commented on src/components/Orders/Orders.js
> +import { useDispatch, useSelector } from "react-redux";
doesn't appear that useSelector is being used in the code base

2020-05-15 00:55 UTC, erferguson commented on src/components/Orders/Orders.js
> +import { Table, Tag, Button } from "antd";
Tag and Button not called in code

2020-05-15 00:55 UTC, erferguson commented on src/components/Orders/Orders.js
> +import { connect } from "react-redux";
connect not called in code, remove?

2020-05-15 00:55 UTC, erferguson commented on src/components/SellerAccount/SellerAccount.js
> +// import Nav from '../elements/nav';
remove if not using

2020-05-18 22:46 UTC, mjedwards commented
made the suggested corrections

2020-05-19 02:30 UTC, Cireimu requested changes
Personally cannot approve this right now. It seems to be just a quick thing of flexbox or something but items just float off the screen, also have a ton of horizontal and the sizes vary drastically. Also, images should have standard sizing with max-width, upon loading this page I had two items that took up the entire screen. I can work with you on these things if needed but I need this to be fixed first before I can merge them.  
![inventory screen](https://user-images.githubusercontent.com/51389138/82277936-e4dd8900-993d-11ea-9f2f-0673571952dd.PNG)

2020-05-20 00:36 UTC, mjedwards commented
Everything should be fixed now.

2020-05-20 00:52 UTC, merged